mydata<-read.csv("household_power_consumption.txt", header = T, sep = ';', na.strings = "?")
mydata$Date <- as.Date(mydata$Date, format = "%d/%m/%Y")
mydata<- subset(mydata, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
dt<- paste(as.Date(mydata$Date), mydata$Time)
mydata$datetime <- as.POSIXct(dt)
mydata$Global_active_power <- as.numeric(as.character(mydata$Global_active_power))
mydata$Global_active_power <- as.numeric(as.character(mydata$Sub_metering_1))
mydata$Global_active_power <- as.numeric(as.character(mydata$Sub_metering_2))
mydata$Global_active_power <- as.numeric(as.character(mydata$Sub_metering_3))
dt<- paste(as.Date(mydata$Date), mydata$Time)
mydata$datetime <- as.POSIXct(dt)
par(mfrow=c(2,2))
plot(mydata$datetime,mydata$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(mydata$datetime,mydata$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(mydata$datetime,mydata$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(mydata$datetime,mydata$Sub_metering_2,col="red")
lines(mydata$datetime,mydata$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), bty="n", cex=.5) #bty removes the box, cex shrinks the text, spacing added after labels so it renders correctly
plot(mydata$datetime,mydata$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()