mydata<-read.csv("household_power_consumption.txt", header = T, sep = ';', na.strings = "?")
mydata$Date <- as.Date(mydata$Date, format = "%d/%m/%Y")
mydata<- subset(mydata, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
dt<- paste(as.Date(mydata$Date), mydata$Time)
mydata$datetime <- as.POSIXct(dt)
mydata$Global_active_power <- as.numeric(as.character(mydata$Global_active_power))
dt<- paste(as.Date(mydata$Date), mydata$Time)
mydata$datetime <- as.POSIXct(dt)
plot(mydata$datetime,mydata$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.copy(png, file="plot2.png", width=480, height=480)
dev.off()