mydata<-read.csv("household_power_consumption.txt", header = T, sep = ';', na.strings = "?")
mydata$Date <- as.Date(mydata$Date, format = "%d/%m/%Y")
mydata<- subset(mydata, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
dt<- paste(as.Date(mydata$Date), mydata$Time)
mydata$datetime <- as.POSIXct(dt)
mydata$Global_active_power <- as.numeric(as.character(mydata$Global_active_power))
mydata$Global_active_power <- as.numeric(as.character(mydata$Sub_metering_1))
mydata$Global_active_power <- as.numeric(as.character(mydata$Sub_metering_2))
mydata$Global_active_power <- as.numeric(as.character(mydata$Sub_metering_3))
dt<- paste(as.Date(mydata$Date), mydata$Time)
mydata$datetime <- as.POSIXct(dt)
plot(mydata$datetime,mydata$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(mydata$datetime,mydata$Sub_metering_2,col="red")
lines(mydata$datetime,mydata$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()
dev.off()